# Generated by Django 2.2.3 on 2019-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dog_name',
            field=models.TextField(default='taro', max_length=100),
            preserve_default=False,
        ),
    ]
