# Generated by Django 2.2.3 on 2019-07-11 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dog_name',
        ),
    ]
