# Generated by Django 2.2.3 on 2019-08-16 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0001_initial'),
        ('users', '0003_remove_user_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stp.Dealer'),
        ),
    ]
