# Generated by Django 2.2.3 on 2019-07-16 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('incl', models.IntegerField()),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='stp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos', models.IntegerField(default=0)),
                ('item', models.ForeignKey(default=stp.models.get_or_create_item, on_delete=django.db.models.deletion.CASCADE, to='stp.Item')),
                ('order', models.ForeignKey(default=stp.models.get_or_create_order, on_delete=django.db.models.deletion.CASCADE, to='stp.Order')),
                ('user', models.ForeignKey(default=stp.models.get_or_create_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
