# Generated by Django 2.2.3 on 2019-08-16 01:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=30)),
                ('abb_name', models.CharField(default='no abb_name', max_length=10)),
                ('dealer_code', models.CharField(default='00000', max_length=5)),
                ('zip_code', models.CharField(default='0000000', max_length=7)),
                ('address', models.CharField(default='no address', max_length=100)),
                ('telephone', models.CharField(default='00000000000', max_length=11)),
                ('recipient', models.CharField(default='no recipient', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_dispatched', models.BooleanField(default=False)),
                ('tracking_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_placed', models.BooleanField(default=False)),
                ('dealer_name', models.CharField(default='no name', max_length=30)),
                ('zip_code', models.CharField(default='0000000', max_length=7)),
                ('address', models.CharField(default='no address', max_length=100)),
                ('telephone', models.CharField(default='00000000000', max_length=11)),
                ('recipient', models.CharField(default='no recipient', max_length=20)),
                ('campaign', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Campaign')),
                ('order_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('incl', models.IntegerField(default=1)),
                ('thresh_auto_app', models.IntegerField(default=0)),
                ('thresh_stock_alert', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_set', to='stp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stp.Item')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
