# Generated by Django 2.2.3 on 2019-07-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='incl',
        ),
    ]
