# Generated by Django 2.2.3 on 2019-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0002_remove_item_incl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='incl',
            field=models.IntegerField(default=1),
        ),
    ]
