# Generated by Django 2.2.3 on 2019-07-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Item'),
        ),
    ]
