# Generated by Django 2.2.3 on 2019-07-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0003_item_incl'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thresh_auto_app',
            field=models.IntegerField(default=0),
        ),
    ]
