# Generated by Django 2.2.3 on 2019-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0004_item_thresh_auto_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thresh_stock_alert',
            field=models.IntegerField(default=0),
        ),
    ]
