# Generated by Django 2.2.3 on 2019-07-11 13:14

from django.db import migrations, models
import django.db.models.deletion
import stp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0004_basketitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(default=stp.models.get_or_create_item, on_delete=django.db.models.deletion.CASCADE, to='stp.Item'),
        ),
    ]
