# Generated by Django 2.2.3 on 2019-07-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0005_auto_20190711_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='nos',
            field=models.IntegerField(null=True),
        ),
    ]
