# Generated by Django 2.2.3 on 2019-08-12 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0005_item_thresh_stock_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stp.Item'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='nos',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
