# Generated by Django 2.2.3 on 2019-08-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0007_auto_20190812_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stp.Item'),
        ),
    ]
