# Generated by Django 2.2.3 on 2019-08-14 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0008_auto_20190812_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Order'),
        ),
    ]
