# Generated by Django 2.2.3 on 2019-07-12 11:51

from django.db import migrations, models
import django.db.models.deletion
import stp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='order',
            field=models.ForeignKey(default=stp.models.get_or_create_order, on_delete=django.db.models.deletion.CASCADE, to='stp.Order'),
        ),
    ]
