# Generated by Django 2.2.3 on 2019-08-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0009_auto_20190814_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Order'),
        ),
    ]
