# Generated by Django 2.2.3 on 2019-07-12 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stp', '0009_basketitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='user',
            field=models.ForeignKey(default=stp.models.get_or_create_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
