# Generated by Django 2.2.3 on 2019-07-12 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0011_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=stp.models.get_or_create_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
