# Generated by Django 2.2.3 on 2019-08-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0011_auto_20190815_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tmc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
