# Generated by Django 2.2.3 on 2019-07-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0014_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
