# Generated by Django 2.2.3 on 2019-08-15 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0015_order_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='campaign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stp.Campaign'),
        ),
    ]
