# Generated by Django 2.2.3 on 2019-08-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0016_auto_20190815_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tmc_approved',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dispatched',
            new_name='is_dispatched',
        ),
        migrations.AddField(
            model_name='order',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
