# Generated by Django 2.2.3 on 2019-08-15 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0017_auto_20190815_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_placed',
        ),
    ]
