# Generated by Django 2.2.3 on 2019-08-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0018_remove_order_is_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
